# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

# Add 'repo' label to any root file changes
repo:
- '*'

# Add 'bashscript' label to any change to *.sh files within the root dir
bashscript:
- '*.sh'

# Add 'readme' label to any change to README.md files within the root dir
readme:
- 'README.md'

# Add 'media' label to any change to media files within the media dir
media:
- 'media/**'
